/**
 * Configuração central e esquema do banco de dados.
 * Todas as abas são criadas e mantidas por setupSystem().
 */
var APP_CONFIG = Object.freeze({
  APP_NAME: 'CozinhaFlow Tarefas',
  COMPANY_NAME: 'Minha Cozinha Industrial',
  VERSION: '1.5.0',
  TIMEZONE: 'America/Sao_Paulo',
  SESSION_TTL_SECONDS: 21600,
  REMEMBER_TTL_SECONDS: 2592000,
  CACHE_TTL_SECONDS: 180,
  LOCK_TIMEOUT_MS: 30000,
  PASSWORD_MIN_LENGTH: 8,
  MAX_PAGE_SIZE: 200
});

var SHEETS = Object.freeze({
  CONFIG: ['CHAVE', 'VALOR', 'DESCRICAO', 'ATUALIZADO_EM'],
  USUARIOS: ['ID', 'NOME', 'EMAIL', 'SENHA_HASH', 'SALT', 'PERFIL', 'STATUS', 'ULTIMO_ACESSO', 'CRIADO_EM', 'ATUALIZADO_EM'],
  OPERADORES: ['ID', 'FOTO', 'NOME', 'TELEFONE', 'EMAIL', 'PIN_HASH', 'CARGO', 'FUNCAO', 'PERMISSAO', 'STATUS', 'ULTIMO_ACESSO', 'CRIADO_EM', 'ATUALIZADO_EM'],
  TAREFAS: ['ID', 'TITULO', 'DESCRICAO', 'RESPONSAVEL_ID', 'RESPONSAVEL_NOME', 'RESPONSAVEL_EMAIL', 'PRIORIDADE', 'PRAZO', 'STATUS', 'CRIADO_POR_ID', 'CRIADO_POR_NOME', 'INICIADO_EM', 'CONCLUIDO_EM', 'CONFIRMADO', 'FOTO_ID', 'FOTO_URL', 'OBSERVACAO_CONCLUSAO', 'CRIADO_EM', 'ATUALIZADO_EM'],
  INSUMOS: ['ID', 'CODIGO', 'NOME', 'CATEGORIA', 'FORNECEDOR_PREFERENCIAL', 'UNIDADE', 'FOTO', 'CODIGO_BARRAS', 'QR_CODE', 'PRECO_MEDIO', 'PRECO_ATUAL', 'PRECO_ANTERIOR', 'ESTOQUE_MINIMO', 'ESTOQUE_MAXIMO', 'LOCALIZACAO', 'VALIDADE_PADRAO', 'OBSERVACOES', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
  PRODUTOS: ['ID', 'CODIGO', 'NOME', 'CATEGORIA', 'FOTO', 'CODIGO_BARRAS', 'QR_CODE', 'UNIDADE', 'PRECO_VENDA', 'CUSTO', 'MARGEM', 'ESTOQUE_MINIMO', 'ESTOQUE_MAXIMO', 'VALIDADE_PADRAO', 'RECEITA_ID', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM', 'PESO_UNITARIO', 'UNIDADE_PESO'],
  RECEITAS: ['ID', 'PRODUTO_ID', 'NOME', 'MODO_PREPARO', 'TEMPO_MIN', 'RENDIMENTO', 'UNIDADE_RENDIMENTO', 'PERDA_PREVISTA_PCT', 'CUSTO_TOTAL', 'CUSTO_UNIDADE', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
  RECEITAS_ITENS: ['ID', 'RECEITA_ID', 'INSUMO_ID', 'QUANTIDADE', 'UNIDADE', 'CUSTO_UNITARIO', 'CUSTO_TOTAL', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
  MOVIMENTACOES: ['ID', 'TIPO_ESTOQUE', 'ITEM_ID', 'LOTE_ID', 'TIPO', 'QUANTIDADE', 'VALOR_UNITARIO', 'SALDO_ANTES', 'SALDO_DEPOIS', 'REFERENCIA_TIPO', 'REFERENCIA_ID', 'OPERADOR_ID', 'JUSTIFICATIVA', 'DATA_HORA'],
  PRODUCOES: ['ID', 'CODIGO', 'PRODUTO_ID', 'RECEITA_ID', 'QTD_PLANEJADA', 'QTD_PRODUZIDA', 'QTD_PERDIDA', 'LOTE', 'OPERADOR_ID', 'HORA_INICIO', 'HORA_FIM', 'TEMPO_MIN', 'OBSERVACOES', 'STATUS', 'CUSTO_TOTAL', 'CRIADO_EM', 'ATUALIZADO_EM', 'PESO_UNITARIO_PRODUTO', 'UNIDADE_PESO_PRODUTO', 'PESO_TOTAL_PRODUZIDO_KG', 'RENDIMENTO_PACOTES_KG', 'APROVEITAMENTO_PCT'],
  PRODUCAO_ITENS: ['ID', 'PRODUCAO_ID', 'INSUMO_ID', 'LOTE_ID', 'QTD_PREVISTA', 'QTD_CONSUMIDA', 'CUSTO_UNITARIO', 'CUSTO_TOTAL', 'CRIADO_EM'],
  ESTOQUE: ['ID', 'INSUMO_ID', 'LOTE', 'VALIDADE', 'QUANTIDADE_INICIAL', 'QUANTIDADE_ATUAL', 'CUSTO_UNITARIO', 'FORNECEDOR_ID', 'LOCALIZACAO', 'ENTRADA_EM', 'STATUS'],
  ESTOQUE_PRODUTOS: ['ID', 'PRODUTO_ID', 'LOTE', 'VALIDADE', 'QUANTIDADE_INICIAL', 'QUANTIDADE_ATUAL', 'CUSTO_UNITARIO', 'LOCALIZACAO', 'ENTRADA_EM', 'STATUS'],
  COMPRAS: ['ID', 'CODIGO', 'INSUMO_ID', 'CATEGORIA', 'FORNECEDOR_ID', 'ESTOQUE_ATUAL', 'ESTOQUE_MINIMO', 'QUANTIDADE_SUGERIDA', 'QUANTIDADE_APROVADA', 'STATUS', 'SOLICITANTE_ID', 'APROVADOR_ID', 'DATA', 'OBSERVACOES', 'CRIADO_EM', 'ATUALIZADO_EM'],
  PEDIDOS: ['ID', 'NUMERO', 'FORNECEDOR_ID', 'VALOR_TOTAL', 'RESPONSAVEL_ID', 'DATA', 'PREVISAO_ENTREGA', 'NOTA_FISCAL', 'OBSERVACOES', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
  PEDIDOS_ITENS: ['ID', 'PEDIDO_ID', 'INSUMO_ID', 'QUANTIDADE', 'QUANTIDADE_RECEBIDA', 'PRECO', 'VALOR_TOTAL', 'LOTE', 'VALIDADE', 'DIVERGENCIA', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
  FORNECEDORES: ['ID', 'CODIGO', 'RAZAO_SOCIAL', 'NOME_FANTASIA', 'CNPJ', 'INSCRICAO_ESTADUAL', 'TELEFONE', 'WHATSAPP', 'EMAIL', 'ENDERECO', 'CIDADE', 'ESTADO', 'CEP', 'CONTATO', 'PRODUTOS_FORNECIDOS', 'PRAZO_MEDIO_DIAS', 'AVALIACAO', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
  PERDAS: ['ID', 'TIPO_ESTOQUE', 'ITEM_ID', 'QUANTIDADE', 'MOTIVO', 'CATEGORIA', 'FOTO', 'OPERADOR_ID', 'SUPERVISOR_ID', 'LOTE_ID', 'DATA_HORA', 'CUSTO', 'STATUS', 'CUSTO_UNITARIO', 'UNIDADE'],
  INVENTARIOS: ['ID', 'NUMERO', 'TIPO', 'TIPO_ESTOQUE', 'ITEM_ID', 'SALDO_ESPERADO', 'QUANTIDADE_CONTADA', 'DIFERENCA', 'OPERADOR_ID', 'SUPERVISOR_ID', 'MOTIVO', 'FOTO', 'ASSINATURA', 'DATA_HORA', 'STATUS'],
  AJUSTES: ['ID', 'INVENTARIO_ID', 'TIPO_ESTOQUE', 'ITEM_ID', 'LOTE_ID', 'QUANTIDADE', 'JUSTIFICATIVA', 'RESPONSAVEL_ID', 'DATA_HORA'],
  AUDITORIA: ['ID', 'ACAO', 'USUARIO_ID', 'USUARIO_NOME', 'TELA', 'REGISTRO_TIPO', 'REGISTRO_ID', 'DADOS_ANTES', 'DADOS_DEPOIS', 'OBSERVACAO', 'DATA_HORA'],
  NOTIFICACOES: ['ID', 'TIPO', 'TITULO', 'MENSAGEM', 'SEVERIDADE', 'REFERENCIA_TIPO', 'REFERENCIA_ID', 'LIDA', 'USUARIO_ID', 'CRIADO_EM'],
  FECHAMENTOS: ['ID', 'DATA', 'RESPONSAVEL_ID', 'SUPERVISOR_ID', 'PRODUCAO_QTD', 'PRODUCAO_CUSTO', 'CONSUMO_QTD', 'PERDAS_QTD', 'PERDAS_CUSTO', 'SALDO_ESPERADO', 'SALDO_CONTADO', 'DIFERENCA', 'OBSERVACOES', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
  CONFIGURACOES: ['ID', 'GRUPO', 'CHAVE', 'VALOR', 'DESCRICAO', 'EDITAVEL', 'ATUALIZADO_EM']
});

var ROLES = Object.freeze(['Administrador', 'Supervisor', 'Operador', 'Comprador', 'Financeiro', 'Consulta']);

var ACL = Object.freeze({
  Administrador: ['tarefas', 'operadores', 'notificacoes'],
  Supervisor: ['tarefas', 'notificacoes'],
  Operador: ['tarefas', 'notificacoes'],
  Comprador: ['tarefas', 'notificacoes'],
  Financeiro: ['tarefas', 'notificacoes'],
  Consulta: ['tarefas', 'notificacoes']
});

var ENUMS = Object.freeze({
  STATUS_ATIVO: ['Ativo', 'Inativo'],
  STATUS_COMPRA: ['Solicitado', 'Em análise', 'Aprovado', 'Comprado', 'Recebido', 'Cancelado'],
  STATUS_PEDIDO: ['Rascunho', 'Aprovado', 'Enviado', 'Parcial', 'Recebido', 'Cancelado'],
  STATUS_PRODUCAO: ['Planejada', 'Em produção', 'Finalizada', 'Cancelada'],
  STATUS_TAREFA: ['A fazer', 'Em andamento', 'Concluída', 'Cancelada'],
  PRIORIDADE_TAREFA: ['Baixa', 'Normal', 'Alta', 'Urgente'],
  PERDA_CATEGORIA: ['Quebra', 'Erro', 'Contaminação', 'Sobras', 'Outros'],
  INVENTARIO_TIPO: ['Diário', 'Semanal', 'Mensal', 'Geral', 'Cego'],
  UNIDADES: ['kg', 'g', 'L', 'mL', 'un', 'cx', 'pct', 'porção']
});
